vcs:
  provider: git
  url: git@github.com:go1dshtein/pgv.git
  prefix: tests/data/sql
  include:
    - "schemas/*/types/*.sql"
database:
  isolation_level: autocommit
package:
  format: directory
  path: $PWD/dist/pgv
logging:
  level: DEBUG
  filename: $PWD/build/pgv.log
  bytes: 1000000
  count: 2
