vcs:
  type: git
  url: file://.
  path: test/data
package:
  format: tar.gz
  destination: dist/pgv
  always_include:
    - "schemas/*/type/*.sql"
logging:
  level: INFO
  filename: build/pgv.log
  bytes: 1000000
  count: 2
