vcs:
  provider: git
  url: git@github.com:go1dshtein/pgv.git
  prefix: test/data/sql
package:
  format: directory
  destination: dist/pgv
  always_include:
    - "schemas/*/type/*.sql"
logging:
  level: DEBUG
  filename: build/pgv.log
  bytes: 1000000
  count: 2
