vcs:
  provider: git
  url: git@github.com:go1dshtein/pgv.git
  prefix: tests/data/sql
  include:
    - "schemas/*/types/*.sql"
package:
  format: directory
  path: dist/pgv
logging:
  level: DEBUG
  filename: build/pgv.log
  bytes: 1000000
  count: 2
