.TH PGV-INITDB "JULY 2014"
.SH NAME
pgv initdb - initializes new database for working
.I pgv
.SH SYNOPSYS
.B "pgv initdb"
[--help]
.P
.B "pgv initdb"
[ -o] -d
.I DBNAME
[-h
.I HOST
] [-p
.I PORT
] [-U
.I USERNAME
] [-w|-W]
.SH DESCRIPTION
Also it is needed to initialize versioning in a database.
.B "pgv init"
creates schema in database for tracking changes.
.SH OPTIONS
.IP --help
print help and exit;
.IP "-o --overwrite"
overwrite schema if it already exists in database;
.IP "-d DBNAME --dbname DBNAME"
name of target database;
.IP "-h HOST --host HOST"
database server address;
.IP "-p PORT --port PORT"
database port;
.IP "-U USERNAME --username USERNAME"
database username;
.IP "-w --no-password"
no ask for password;
.IP "-W --password"
ask for password.
.SH EXAMPLES
.PP
Before pushing changes to database, you should initialize it:
.RS
pgv init -d mydb -h test -U test
.RE
.SH SEE ALSO
.BR pgv (1)
