.TH PGV-INIT 1 "JULY 2014"
.SH NAME
pgv init - initializes repository in the current directory.
.SH SYNOPSYS
.B "pgv init"
[--help]
.P
.B "pgv init"
[-p
.I PATH
]
.SH DESCRIPTION
.B "pgv init"
prepare working directory.
It creates schemas directory with right structure and
minimal configuration file in the current directory.
.SH OPTIONS
.IP --help
print help and exit;
.IP "-p PATH --prefix PATH"
relative path to schemas directory.
.SH EXAMPLES
For example, you start new project and want store database schema in ./database/sql folder, so
.RS
pgv init -p database/sql
.RE
.SH SEE ALSO
.BR pgv (1)
